---
- name: Display CPU info
  block:
    - name: Display CPU Information
      debug:
        var: ansible_processor

    - name: Display CPU Core Count
      debug:
        var: ansible_processor_cores

    - name: Display Hyper-Threading Information
      debug:
        var: ansible_processor_threads_per_core
