---
- block:
    - name: Enable processor.max_cstate if not exists
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="((?:(?!processor.max_cstate=\d).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX="\1 processor.max_cstate=0"'
        backup: true
        backrefs: true
      notify: reboot after update

    - name: Enable processor.max_cstate if exists but disabled
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=(.*)processor.max_cstate=0(.*)$'
        line: 'GRUB_CMDLINE_LINUX=\1processor.max_cstate=1\2'
        backup: true
        backrefs: true
      notify: reboot after update
  become: true

- block:
    - name: Install cpufrequtils
      ansible.builtin.package:
        name:
          - cpufrequtils
        state: latest
    - name: Turn on performance mode
      shell: |
        touch /etc/default/cpufrequtils
        echo 'GOVERNOR="performance"' | sudo tee /etc/default/cpufrequtils
        systemctl disable ondemand
        systemctl restart cpufrequtils
      notify: reboot after update
  become: true